### ISSUE TITLE
How about adding to the source compatibility suite?

### ISSUE THREAD

**Issue by linqingmo** [line/line-sdk-ios-swift#6] opened 2018-11-30 01:15 UTC
Swift 5.0 regression. [SR-9375](https://bugs.swift.org/browse/SR-9375?filter=-2)

**Comment by onevcat** [comment] 2018-11-30 01:31
Thanks for reporting it.

Obviously, it turns to be a Swift 5.0 regression.

I will try to confirm it in the snapshot toolkit later, and send a PR to source compatibility repo to contain it to the regression test suite if necessary.

**Comment by onevcat** [comment] 2018-12-03 01:54
We made a small workaround to make it compile for Swift development toolchain snapshot you mentioned. However, we are still seeing some crash in our unit tests when we use the snapshot version. And the same issue is happening in the sample app. So I guess it is not a good time to use this framework with that Swift compiler since we didn't have a good time to run full tests for it.

I am closing this issue now.

**Closed by onevcat** 2018-12-03 01:54 UTC

**Comment by onevcat** [comment] 2019-01-07 03:00
This issue should be already fixed in Swift: https://github.com/apple/swift/pull/21296
